modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
logoFile="rosewood.png"
authors="five & bageldotjpg" #optional
credits="Thanks for this example mod goes to Java"

[[mods]]
modId="atmospheric"
version="${file.jarVersion}"
displayName="Atmospheric"
description='''
Adds a unique biome, with a new wood type and new plants.
There will continue to be more biomes over time!
'''

[[dependencies.atmospheric]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.atmospheric]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
