modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (31 is current forge version)
logoFile="logo.png"
authors="five & bageldotjpg" #optional
credits="Jackson for CurseForge page & Logo"

[[mods]]
modId="atmospheric"
version="${file.jarVersion}"
displayName="Atmospheric"
description='''
Adds a unique biome, with a new wood type and new plants.
There will continue to be more biomes over time!
'''

[[dependencies.atmospheric]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.atmospheric]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"
