modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (31 is current forge version)
logoFile="logo.png"
authors="five & bageldotjpg" #optional
credits="Jackson for CurseForge page & Logo"

[[mods]]
modId="atmospheric"
version="${file.jarVersion}"
displayName="Atmospheric"
description='''
Adds two unique biome types with several variants.
Also introduces several new types of blocks, foliage, and plants!
There will continue to be more biomes over time!'''

[[dependencies.atmospheric]]
    modId="forge"
    mandatory=true
    versionRange="[31.1.46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.atmospheric]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[1.0.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.atmospheric]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
