modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/atmospheric/issues"
license = "https://github.com/team-abnormals/atmospheric/blob/main/LICENSE.txt"

[[mods]]
    modId = "atmospheric"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "atmospheric:passion_fruit"
    configBackground = "atmospheric:textures/block/arid_sand.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg, five"
    displayURL = "https://www.teamabnormals.com/mods/atmospheric"
    displayName = "Atmospheric"
    description = '''
    Adds two unique biome types with several variants.
    Also introduces several new types of blocks, foliage, and plants!
    There will continue to be more biomes over time!
    '''

[[dependencies.atmospheric]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.atmospheric]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.atmospheric]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.0.3,)"
    ordering = "AFTER"
    side = "BOTH"